---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/inventory_mgmt
    username: root
    password: "Sayyad"
  jpa:
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
contact-info:
  contactNumber: +91-11111111111
  emailAddress: contact-us@motorcorp.com
server:
  port: 8080
  eureka:
    client:
      register-with-eureka: true
      fetch-registry: false
      service-url:
        defaultZone: http://localhost:7001/eureka, http://localhost:7002/eureka
...
---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/inventory_mgmt
    username: root
    password: "Sayyad"
  jpa:
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
contact-info:
  contactNumber: +91-888888888888
  emailAddress: no-test-reply@motorcorp.com
server:
  port: 8081
eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:7001/eureka, http://localhost:7002/eureka